# docker compose
version: '3'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${FQDN}
    ports:
      - "${PORT}:80"
    volumes:
      -  ${SHARE}:/mnt/smb
